### ISSUE TITLE
collegamenti ipertestuali

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/MyWebSite#3]
```html
<a>file:///home/manjaro/MyWebSite/ricetta.html</a>
```
Questo come sai non va bene.
1. Devi leggere bene come si creano i collegamenti ipertestuali
2. I collegamenti devono essere relativi e non assoluti

**Comment by tonyiovino** [comment]
Okay... Quindi? Ora vado leggere come si fanno, ma non ho ben capito cosa intendete tra relativo e assoluto.

**Comment by FabioZTessitore** [comment]
si è parlato di questa differenza in "Esplorare il filesystem", dovresti averlo letto

**Comment by tonyiovino** [comment]
Si, ricordo, pensavo fosse qualcosa per html

**Comment by tonyiovino** [comment]
Ma li collego a git hub?

**Comment by FabioZTessitore** [comment]
Che c'entra GitHub. Devi mettere percorsi relativi

Il mar 25 giu 2019, 12:48 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Con il comando: "<a>....</a>"?

**Comment by tonyiovino** [comment]
<a*>

**Comment by FabioZTessitore** [comment]
Prima di tutto devi capire come si fanno i collegamenti

Il mar 25 giu 2019, 13:03 tonyiovino <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Non basta

Il mar 25 giu 2019, 13:04 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Ah...

**Comment by tonyiovino** [comment]
Intendete per caso "<p>"?

**Comment by tonyiovino** [comment]
<p>*

**Comment by tonyiovino** [comment]
<p*>

**Comment by FabioZTessitore** [comment]
No no. Vatti a rileggere come si fa

Il mar 25 giu 2019, 13:08 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Okk

**Comment by tonyiovino** [comment]
_<p><a href="http://www.htmldog.com">HTML Dog</a></p>_
Questo è l'esempio.

**Comment by tonyiovino** [comment]
Ah, ora ho capito.

**Comment by tonyiovino** [comment]
Ovviamente devo lavorare su "ricetta.html"

**Comment by FabioZTessitore** [comment]
Devi lavorare su tutto

Il mar 25 giu 2019, 13:22 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Ovviamente.

**Comment by FabioZTessitore** [comment]
```html
<a href="file:///home/manjaro/MyWebSite/ricetta.html">
```
Perché non va bene:
I file html si usano per costruire siti web. Una volta che hai creato i tuoi file devi caricarli su un server. Secondo te sul server il file ricetta.html finirà nella directory `home/manjaro/MyWebSite`?
Devi usare percorsi relativi. Siccome ricetta.html sta nella stessa directory di index.html basta scrivere:
```html
<a href="ricetta.html">
```

**Comment by tonyiovino** [comment]
Ah, okay.
