### ISSUE TITLE
ricetta

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/MyWebSite#4]
non va bene. Leggi bene il testo dell'esercizio e utilizza gli elementi necessari

**Comment by tonyiovino** [comment]
Okay

**Comment by FabioZTessitore** [comment]
che stai combinando?

**Comment by tonyiovino** [comment]
...😅

Il Sab 29 Giu 2019 08:27 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by tonyiovino** [comment]
Scusate per l'assenza, un po' la stanchezza provocata dal caldo, un po' la comunione di mio fratello che non sono riuscito a fare nulla.

**Comment by tonyiovino** [comment]
Ho riordinato tutto in un file, come dovevo fare.
