### ISSUE TITLE
usare i tag giusti

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/MyWebSite#6]
```html
<p><em>La Frittata Di Maccheroni</em></p>
```

che volevi fare? probabilmente c'è un tag giusto per fare quello che ti serve

anche qui:
```html
<p>1- Spaghetti.</p>
			<p>2- 6 uova.</p>
			<p>3- formaggio.</p>
			<p>4- sale.</p>
			<p>5- pepe.</p>
<p>6- olio.</p>
```

**Comment by tonyiovino** [comment]
Ehm... Quali

**Comment by tonyiovino** [comment]
?*

**Comment by FabioZTessitore** [comment]
Il testo dell'esercizio dice:

ricetta.html:
contiene un'intestazione, una piccola descrizione della ricetta, la lista degli ingredienti, i passi per la preparazione;

iniziamo dalla prima: un'intestazione. Come si fa?

**Comment by tonyiovino** [comment]
Non saprei...

**Comment by FabioZTessitore** [comment]
vai a rivedere le lezioni

**Comment by tonyiovino** [comment]
Che si intende per "intestazione"?

**Comment by FabioZTessitore** [comment]
ah l'italiano ...

**Comment by tonyiovino** [comment]
Esiste anche d'estate?

Il Gio 4 Lug 2019 15:59 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by tonyiovino** [comment]
Intendete questo? http://www.vincenzoscognamiglio.it/informatica/tag/intestazione/

**Comment by FabioZTessitore** [comment]
Ma che c'entra sta roba.
Ti ricordo che stai facendo un esercizio con l'html e che sul sito ci sono
alcune spiegazioni e la guida di base di htmldog

Il mar 9 lug 2019, 20:44 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Voi volete che io faccia un'intestazione?

**Comment by tonyiovino** [comment]
Su "ricetta.html"?

**Comment by FabioZTessitore** [comment]
È una delle cose richieste

Il mar 9 lug 2019, 20:52 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Quindi, >ricetta.html</ è apposto? O ci manca qualcosa che non ho inserito?

**Comment by FabioZTessitore** [comment]
Non ci stiamo capendo. Nel file ricetta.html ci vuole un'intestazione più
tutte le altre cose scritte nel testo dell'esercizio

Il mar 9 lug 2019, 20:55 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Okay, ho capito, ma cosa devo scrivere nell'intestazione?

**Comment by FabioZTessitore** [comment]
Va bene anche frittata di maccheroni come hai fatto, ma deve essere
un'intestazione

Il mar 9 lug 2019, 20:59 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Vabene. Dovrebbe anche premiare l'originalità della ricetta HAHAHA

**Comment by tonyiovino** [comment]
Penso che ora vada bene, altrimenti sono una capra, scusatemi.

**Comment by FabioZTessitore** [comment]
Beeeee

A parte gli scherzi, almeno abbiamo individuato come si fanno le
intestazioni.
Due osservazioni:
1) non serve <p> intorno ad un'intestazione
2) quella è l'intestazione principale quindi dovrebbe essere h1

Il mar 9 lug 2019, 21:17 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Va beninsito, ceno e mi metto all'opera.

Il Mar 9 Lug 2019 21:21 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by tonyiovino** [comment]
Avevo il T9 attivato... (beninsito)

**Comment by tonyiovino** [comment]
Ecco fatto.

**Comment by FabioZTessitore** [comment]
Andiamo avanti. L'esercizio dice di aggiungere una piccola descrizione della ricetta. Tu hai scritto:
```html
<p><h4>Descrizione:</h4></p>
<p>La frittata di maccheroni ...</p>
```
Il paragrafo contenente la descrizione va bene, mentre l'intestazione no. Prima di tutto non ci vuole `<p>` come già ti ho detto. Poi, siccome questa è un'intestazione di secondo livello, meglio mettere h2 e non h4.

Ps. puoi aggiungere intestazioni di secondo livello anche per la lista degli ingredienti e per i passi di preparazione

**Comment by tonyiovino** [comment]
Aah, ora ho capito!

Il Mer 10 Lug 2019 17:08 Fabio Z Tessitore <notifications@github.com> ha
scritto:

**Comment by tonyiovino** [comment]
Fatto.

**Comment by FabioZTessitore** [comment]
ok. Come ultima cosa bisogna aggiustare la lista degli ingredienti e la preparazione. Devi trovare i tag adatti

**Comment by tonyiovino** [comment]
`<li>.......</li>`
Per "List"?
_Inside the lists, the li tag is used to define each list item._

**Comment by FabioZTessitore** [comment]
Leggi bene "inside the list ... each list item"
Ma come si fa una lista?

**Comment by tonyiovino** [comment]
_The `ul` tag is used to define unordered lists and the `ol` tag is used to define ordered lists. Inside the lists, the `li` tag is used to define each list item._
Questo è il paragrafo, "`ul` definisce la lista, "`ol` per definire altre liste, e "`li` per la lista.

**Comment by tonyiovino** [comment]
"`ul`", "`ol`", "`li`"*

**Comment by FabioZTessitore** [comment]
ok, vediamo come li usi

**Comment by tonyiovino** [comment]
Okay

**Comment by tonyiovino** [comment]
Ho notato subito i cambiamenti del tipo di elenco in base a come si inseriscono i tag.

**Comment by tonyiovino** [comment]
Intendo "`<ul>`" e "`ol`".
Quale devo usare?

**Comment by tonyiovino** [comment]
In base a quello che mi serve?

**Comment by FabioZTessitore** [comment]
ovviamente

**Comment by tonyiovino** [comment]
Intanto ho fatto come più mi sembra giusto.

**Comment by FabioZTessitore** [comment]
infatti è sbagliato

**Comment by tonyiovino** [comment]
Mood, a parte gli scherzi, quali tag devo mettere? E se non potete dirmelo, come posso capire quali mettere? O come metterli?

**Comment by FabioZTessitore** [comment]
i tag sono giusti ma usati male

**Comment by tonyiovino** [comment]
Ok, ho capito (spero).

**Comment by FabioZTessitore** [comment]
ci siamo quasi

**Comment by tonyiovino** [comment]
Ho visto meglio l'esempio. Manca "`</li>`"

**Comment by tonyiovino** [comment]
Ah no...

**Comment by tonyiovino** [comment]
Ok ho trovato un errore.

**Comment by tonyiovino** [comment]
Ps: non vedo l'ora di esercitarmi sul C, quando ho dovuto fare "Endurance" e "Money" ho avuto un po' di difficoltà in più poiché ero abituato al C, mi piace più il C che il Python. Un affermazione che non avrei mai pensato di esporla quando me lo spiegaste, LOL.

**Comment by tonyiovino** [comment]
esporre*

**Comment by FabioZTessitore** [comment]
non ti preoccupare, di C ce n'è tanto

**Comment by tonyiovino** [comment]
Si, lo so, ho sbirciato le altre parti (2, 3 e 4).

**Comment by FabioZTessitore** [comment]
e non è ancora niente

**Comment by tonyiovino** [comment]
Wow! Sapevo che non sarebbe finito lì.
Anche perché il codice Java non l'ho visto, ah si, ho visto un paio di video tutorial (tra cui anche i suoi) che spiegano Java (i principi di base: creare classi e chiamarle).

**Comment by FabioZTessitore** [comment]
lascia perdere Java per il momento

**Comment by FabioZTessitore** [comment]
comunque, ricetta.html va bene e chiudo questa issue
