### ISSUE TITLE
login.html

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/MyWebSite#8]

**Comment by FabioZTessitore** [comment]
Il login contiene un form con vari elementi

**Comment by tonyiovino** [comment]
Sembra difficile...

**Comment by FabioZTessitore** [comment]
iniziamo a creare un form vuoto

**Comment by tonyiovino** [comment]
Va bene.

**Comment by tonyiovino** [comment]
Fatto

**Comment by FabioZTessitore** [comment]
pensi di condividere?

**Comment by tonyiovino** [comment]
Uh, si.

**Comment by FabioZTessitore** [comment]
ora aggiungiamo un campo di testo per chiedere l'email all'utente (il campo deve essere di tipo testo)

**Comment by tonyiovino** [comment]
`<input type="text">`?

**Comment by FabioZTessitore** [comment]
quasi, manca name

**Comment by tonyiovino** [comment]
Va bene così?

**Comment by FabioZTessitore** [comment]
hai fatto sparire il form?

poi aggiungi il campo password

**Comment by tonyiovino** [comment]
Fatto.

**Comment by FabioZTessitore** [comment]
deve essere password

**Comment by tonyiovino** [comment]
Il type?

**Comment by FabioZTessitore** [comment]
Si

Il sab 13 lug 2019, 22:49 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Fatto

**Comment by FabioZTessitore** [comment]
prosegui con gli altri campi, vediamo che esce

**Comment by tonyiovino** [comment]
Va bien

**Comment by tonyiovino** [comment]
Che ne dite?

**Comment by tonyiovino** [comment]
Okay, ho fatto tutto, anche `<p>Torna nella <a href="index.html">Home Page</a>.</p>`, e sono le 1:11, direi che è l'ora di andare a dormire, LOL.

**Comment by tonyiovino** [comment]
`<riflesione_della_notte>`Sappiate che io mi diverto molto, infatti lo vedo più come "un gioco che mi porterà al mio obiettvo". Grazie di tutto prof!`</riflesione_della_notte>`

**Comment by FabioZTessitore** [comment]
Guarda come hai imparato a mettere i tag. :)

Il dom 14 lug 2019, 01:16 tonyiovino <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Gli aggiustamenti da fare sono:
- eliminare la lista, qui non c'entra proprio niente. Metti tag p per il momento
- età deve essere un campo di testo
- tutti i campi di input devono avere attributo name

**Comment by tonyiovino** [comment]
Io ora lo condivisa senza il name poiché è una scelta, e quindi non deve scrivere nulla, giusto?
Però si interagisce con il mouse, quindi è sempre una periferica di input. 
HELP!

**Comment by tonyiovino** [comment]
Intendo quella parte dove si deve inserire il titolo di studio.

**Comment by FabioZTessitore** [comment]
di quello che hai scritto non ho capito nulla.
Cmq, manca solo il type all'età e il name al titolo di studio

**Comment by tonyiovino** [comment]
HAHAHA, ci credo.
Comunque volevo sapere se ci voleva il name al titolo di studio, hahaha.

**Comment by tonyiovino** [comment]
Ma è sottinteso ch'è di tipo testo.
Lo devo mettere comuque?

**Comment by FabioZTessitore** [comment]
no. non è un tag input, è select. Devi mettere solo name

**Comment by tonyiovino** [comment]
Intendo in età: è sottinteso il type?
intendo in studio: il name ci và?

**Comment by FabioZTessitore** [comment]
in età devi mettere type perché è input (e come hai visto esistono vari type, es. text, password)

in titolo di studio ci vuole il name come in tutti gli elementi che compongono il form (sennò quel value che hai messo ai vari tag option non serve a niente)

**Comment by tonyiovino** [comment]
Perfetto.

**Comment by FabioZTessitore** [comment]
il name va al select, non agli option

**Comment by tonyiovino** [comment]
Okay

**Comment by tonyiovino** [comment]
Fatto
