### ISSUE TITLE
sport.html

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/MyWebSite#9]

**Comment by tonyiovino** [comment]
Rimango un attimo così che vado a cenare, a dopo. (Buon appetito se dovesse o sta mangiando.)

**Comment by tonyiovino** [comment]
Eccomi.

**Comment by tonyiovino** [comment]
Come posso mettere un immagine dedicato al taekwondo?

**Comment by tonyiovino** [comment]
dedicata*

**Comment by FabioZTessitore** [comment]
Vedi il tutorial

Il mer 10 lug 2019, 22:59 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Ho letto, ma non ho capito...

**Comment by FabioZTessitore** [comment]
Qualcosa avrai capito

Il mer 10 lug 2019, 23:11 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Ora vi faccio vedere che ho combinato...

**Comment by tonyiovino** [comment]
Già ci provai su `ricetta.html`, volevo mettere 'na bella friittata di maccheroni come immagine ma non ci riuscii.

**Comment by FabioZTessitore** [comment]
Hai provato ad aprire la pagina?

**Comment by tonyiovino** [comment]
Se intendete sport.html, si ma mi esce il nome dell'attributo

**Comment by tonyiovino** [comment]
Se intendete HTMLDOG, si ma non ci ho capito tantissimo.

**Comment by FabioZTessitore** [comment]
È probabile che l'indirizzo sia errato. Prova con un'immagine di lorempixel.

**Comment by tonyiovino** [comment]
Con quelle di Lorem funzionano, ma sono casuali.

**Comment by FabioZTessitore** [comment]
Va bene così per ora

**Comment by tonyiovino** [comment]
Va bene.

**Comment by tonyiovino** [comment]
Purtroppo la mia testardagine ha avuto la meglio, mettendo come fissa un'immagine che generava il sito LoremPixel, e da google da "Ispezione Elemento".

**Comment by tonyiovino** [comment]
Va bene così?

**Comment by FabioZTessitore** [comment]
```html
<p><img src="http://lorempixel.com/output/sports-q-c-640-480-8.jpg"></p>
<p><img src="https://www.usbfortebraccio.com/wp-content/uploads/2017/11/corso-taekwondo-1.jpg"
```
Lascia la prima e cancella la seconda (tra l'altro non hai chiuso a destra né il tag img né p)

Per completare questa pagina devi aggiungere una tabella con una classifica inventata da te

**Comment by tonyiovino** [comment]
Va bene, anche se vorrei rimanere la seconda, ma penso la prima perché e del sito Lorem.
Non me ne ero nemmeno accorto di non aver chiuso i tag, talmente della pressione addosso di mia madre, 'ché dovevo spegnere il computer...
Comunque ora risolvo tutto (più o meno).

**Comment by FabioZTessitore** [comment]
se mantieni la seconda va bene, ma deve funzionare

**Comment by tonyiovino** [comment]
Ah vabene allora!

**Comment by tonyiovino** [comment]
Avrei voluto mettere una mia foto dove pratico questo sport, solo che non la trovo hahaha.
Comunque riguardo la classifica, non ho ben capito (come sempre) come si usa.

**Comment by FabioZTessitore** [comment]
e come sempre vai a vedere il tutorial di htmldog

**Comment by tonyiovino** [comment]
Già ho visto, perciò vi ho detto che non ho capito, è vero che sono stupido, ma non fino a questo punto 
HAHAHA

**Comment by tonyiovino** [comment]
Non penso che così vada bene, giusto?

**Comment by FabioZTessitore** [comment]
E' un punto di partenza. Cerca di fare due colonne: una per il colore e l'altra per la descrizione. Ogni colore (con descrizione) deve andare su una propria riga

**Comment by tonyiovino** [comment]
Okay

**Comment by tonyiovino** [comment]
Fatto

**Comment by FabioZTessitore** [comment]
ok, aggiungi una riga con i nomi delle colonne e passiamo alla prossima pagina

**Comment by FabioZTessitore** [comment]
ps. mancano tutte le chiusure dei td

**Comment by tonyiovino** [comment]
Ah, non me ne ero accorto, grazie.

**Comment by tonyiovino** [comment]
Ho fatto, ma per i miei gusti è disordinato.

**Comment by tonyiovino** [comment]
Come posso rimediare?

**Comment by FabioZTessitore** [comment]
per il momento non pensare all'estetica. Bisogna imparare ad utilizzare i tag.

La riga con i nomi delle colonne dovrebbe far parte della tabella, non essere in una tabella a parte

**Comment by tonyiovino** [comment]
Ah ok

**Comment by tonyiovino** [comment]
`                       <tr>
				<td><h3>Cintura</h3></td>
				<td><h3>Descrizione</h3></td>
			</tr>`

**Comment by tonyiovino** [comment]
Va bene se li evidenzio così?

**Comment by FabioZTessitore** [comment]
va bene, ma perché h3? Nella pagina hai già qualche h2?

**Comment by tonyiovino** [comment]
Si

**Comment by FabioZTessitore** [comment]
si ho visto, ok

**Comment by tonyiovino** [comment]
Ecco
